### ISSUE TITLE
.nimble file example in project setup is currently wrong

### ISSUE THREAD

**Issue by insomniacUNDERSCORElemon** [godot-nim/docs#2]
It has the binDir line but is missing the bin line. I checked to see if it'd work without it, and no:

``Error:  Nothing to build. Did you specify a module to build using the `bin` key in your .nimble file?``

**Comment by panno8M** [comment]
Since org members should have the authority to edit the wiki, it would be helpful to edit any information that can fix easily or would be better to have.

**Comment by insomniacUNDERSCORElemon** [comment]
> Since org members should have the authority to edit the wiki

Sorry, I don't see the option. The docs say it should be in the upper-right corner, but it is not.

**Comment by panno8M** [comment]
How about now?

**Comment by insomniacUNDERSCORElemon** [comment]
Also just to be clear:

Are the plusses and green highlighting intended or some sort of pasting artefact from something else? They are inconsistent.

**Comment by panno8M** [comment]
Highlighted are changes specific to gdext. Those that are not are created by Godot's `create new project` menu or by `nimble init`.
